import Head from 'next/head'
import './globals.css'
import { Open_Sans } from '@next/font/google'
import { Navbar } from '@/components/Navbar'


const openSans = Open_Sans({
  subsets: ['latin'],
})

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="pt-br"> 
      <body className={`${openSans.className} bg-black min-h-[100vh]`}>
        <Navbar />
        <main className={`${openSans.className} px-4`}>
          {children}
        </main>
      </body>
    </html>

  )
}
